### ISSUE TITLE
Instantiation of ValidatorFactory leads to performance issues

### ISSUE THREAD

**Issue by benjaminknauer** [thombergs/buckpal#33]
Hi 👋

My team used your book on clean architecture as reference for implementing new microservices. We absolutely love your book and the architecture approach. 

Nevertheless, we want to share a major performance issue we encountered while using your template for the `SefValidating` abstract class:
During load testing, we noticed that our application used a lot of memory and requests took a long time even under small loads. Using profiling, we noticed that creating a `ValidatorFactory` during instantiation of every domain object was the problem.
We solved the issue by adding the `ValidatorFactory` as a static attribute in the abstract class.

Cheers,
Benjamin

https://github.com/thombergs/buckpal/blob/f5a9be50771e77ca66a153bc83c383b32cab738e/src/main/java/io/reflectoring/buckpal/common/SelfValidating.java#L14-L17

**Comment by thombergs** [comment]
Good find, thank you. 

I was aware that this is not the most performant solution, but didn't think it would have that big of an impact.
