### ISSUE TITLE
Could not autowire. No beans of 'SendMoneyUseCase' type found. 

### ISSUE THREAD

**Issue by LiveNathan** [thombergs/buckpal#42]
Hey Tom, how does the SendMoneyUseCase get used in the SendMoneyController if SendMoneyUseCase is not annotated with @Service or similar? Trying to understand the architecture. Thanks!

https://github.com/thombergs/buckpal/blob/dc819c66640be4f42100a622b9e97b1e82ad75a7/src/main/java/io/reflectoring/buckpal/adapter/in/web/SendMoneyController.java#L18C50-L18C50

**Comment by LiveNathan** [comment]
Wait, I think I got it. Annotating SendMoneyService with `@UseCase` makes it a bean. Since it implements SendMoneyUseCase, SendMoneyUseCase becomes a bean. Correct?

**Comment by phungdx** [comment]
> Wait, I think I got it. Annotating SendMoneyService with `@UseCase` makes it a bean. Since it implements SendMoneyUseCase, SendMoneyUseCase becomes a bean. Correct?

lgtm
