### ISSUE TITLE
BookPalApplication failed to start

### ISSUE THREAD

**Issue by LevT2** [thombergs/buckpal#8]
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
> 
> Reason: Failed to determine a suitable driver class
> 
> 
> Action:
> 
> Consider the following:
> 	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
> 	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by thombergs** [comment]
This is fixed now, I added H2 to the classpath. 

The value in this example application lies in the structure of the codebase, though, not in running the application :).
